CS2113-AY1819S1-T16-4/main

docs/DeveloperGuide.adoc

Edition includes target user, value proposition, product scope, use stories, non-functional requirements and glossary

Developer guide_v1.1

---

docs/AboutUs.adoc

Edited names to be of lowercase instead

Updated AboutUs.adoc

---

README.adoc
docs/AboutUs.adoc

Add a Coveralls badge to README.adoc, added AboutUs.adoc

---

README.adoc

codacy badge 

---

src/main/java/seedu/address/logic/commands/FilterCommand.java
src/main/java/seedu/address/logic/parser/FilterCommandParser.java
src/main/java/seedu/address/model/person/Department.java
src/main/java/seedu/address/model/person/Position.java

Resolves #56 issue.
V1.2.2  Updates to Filter Command
- 
- Bug fix: Entering invalid department or position now shows an error message
V1.2.1 Filter Command
-
- New Command `filter`: Filters the listing of employees to list only employees of the specific department
- `filter` Command usage: filter d/DEPARTMENT or filter r/POSITION or filter d/DEPARTMENT r/POSITION

V1.2.2  Updates to Filter Command

---

docs/UserGuide.adoc

Updates:
-
- Fields: Added prefix beside the fields, certain fields were labelled with a hyphen for prefix [those handling the fields can update them accordingly if required]
- Add, Edit and Filter command has been updated accordingly [changed mandatory fields, command usage and examples]

UserGuide Update

---

src/main/java/seedu/address/logic/commands/FilterCommand.java
src/main/java/seedu/address/model/person/EmployeeId.java
src/main/java/seedu/address/model/person/Salary.java
src/test/java/seedu/address/model/person/DepartmentContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/person/PositionContainsKeywordsPredicateTest.java

Updates: 
- Added test files for PositionContainsKeywordPredicate and DepartmentContainsKeywordPredicate
- Updated comments within files

Added test files for filter command and updated comments

---

src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/commands/ModifyAllPayCommand.java
src/main/java/seedu/address/logic/commands/ModifyPayCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/ModifyAllPayCommandParser.java

Included COMMAND_ALIAS for both modifyPay and modifyAllPay command.
CHRS now enable modifying of all the employees pay shown in the list based on filter.

modifyPay V1.3.4

---

docs/UserGuide.adoc
src/main/java/seedu/address/logic/commands/AddRecruitmentPostCommand.java
src/main/java/seedu/address/logic/commands/DeleteRecruitmentPostCommand.java
src/main/java/seedu/address/logic/commands/SelectRecruitmentPostCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java

- Add command alias for addRecruitmentPost, deleteRecruitmentPost, selectRecruitmentPost
- Command alias for addRecruitmentPost : arp
- Command alias for deleteRecruitmentPost : drp
- Command alias for selectRecruitmentPost : srp
- Update user guide

Recruitment v1.3.3

---

docs/UserGuide.adoc
src/test/java/seedu/address/model/person/NameTest.java

Updated the following commands in UserGuide.adoc
- filter
- list
- add
- edit

UserGuide.adoc Update

---

docs/UserGuide.adoc
src/main/java/seedu/address/logic/parser/AddRecruitmentPostCommandParser.java

- Update User guide
- Update token size in addRecruitmentPostParser to protect parser

Recruitment v1.3.6

---

docs/UserGuide.adoc

Update User guide

---

src/main/java/seedu/address/commons/events/ui/NewMenuBarCmdClickedEvent.java
src/main/java/seedu/address/ui/CommandBox.java
src/main/java/seedu/address/ui/MainWindow.java

- When menu items clicked, edit text sets the command word, cursor points to the end of the word.

V1.3.11 menu bar upgraded

---

docs/UserGuide.adoc
src/main/java/seedu/address/logic/parser/ModifyAllPayCommandParser.java
src/main/java/seedu/address/logic/parser/ModifyPayCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/person/Bonus.java

Updated bonus and user guide

---

src/main/java/seedu/address/logic/parser/FilterCommandParser.java

Command bug allowing more than one d/ or one r/ appearing have been fixed

Bug fixed for FilterCommand

---

src/main/java/seedu/address/model/recruitment/JobDescription.java
src/main/java/seedu/address/model/recruitment/Post.java

- Update constrain message for post and job description.

Update constrain msg

---

src/main/java/seedu/address/logic/parser/AddExpensesCommandParser.java

Expenses bug fix

---

src/main/java/seedu/address/logic/commands/ModifyAllPayCommand.java

Resolved modifyAllPay issue identified in #213

Bug fix for modifyAllPay

---

src/main/java/seedu/address/logic/commands/ModifyAllPayCommand.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/ModifyAllPayCommandTest.java
src/test/java/seedu/address/testutil/ModAllSalaryDescriptorBuilder.java

ModifyAllPayCommand Test Files included

New Test Files

---

docs/DeveloperGuide.adoc

Added tags under instructions for manual testing, do include your own commands in the tags, it has your name.

DeveloperGuide Update

---

src/main/java/seedu/address/model/schedule/Schedule.java
src/test/java/seedu/address/model/schedule/ScheduleTest.java
src/test/java/seedu/address/model/schedule/TypeTest.java
src/test/java/seedu/address/testutil/schedule/TypicalSchedules.java

Bug fix on delete leaves not working

V1.4.3 bug fix 

---

src/main/java/seedu/address/logic/commands/AddLeavesCommand.java
src/main/java/seedu/address/logic/commands/AddScheduleCommand.java
src/main/java/seedu/address/logic/commands/AddWorksCommand.java
src/main/java/seedu/address/logic/commands/CalculateLeavesCommand.java
src/main/java/seedu/address/logic/commands/ClearCommand.java
src/main/java/seedu/address/logic/commands/ClearScheduleCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/DeleteLeavesCommand.java
src/main/java/seedu/address/logic/commands/DeleteScheduleCommand.java
src/main/java/seedu/address/logic/commands/DeleteWorksCommand.java
src/main/java/seedu/address/logic/commands/RedoCommand.java
src/main/java/seedu/address/logic/commands/SelectScheduleCommand.java
src/main/java/seedu/address/logic/commands/UndoCommand.java
src/main/java/seedu/address/logic/parser/AddScheduleCommandParser.java
src/main/java/seedu/address/logic/parser/AddWorksCommandParser.java
src/main/java/seedu/address/logic/parser/DeleteScheduleCommandParser.java
src/main/java/seedu/address/model/schedule/Date.java
src/main/java/seedu/address/model/schedule/DateComparator.java
src/main/java/seedu/address/model/schedule/EmployeeIdComparator.java
src/main/java/seedu/address/model/schedule/Type.java
src/main/java/seedu/address/model/schedule/Year.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/resources/view/MainWindow.fxml
src/test/java/seedu/address/logic/commands/AddScheduleCommandTest.java
src/test/java/seedu/address/ui/MenuBarTest.java

**Java adoc comment updated**
1. /Logic/Commands
- AddSchedule, DeleteSchedule, AddLeaves, AddWorks, DeleteLeaves,DeleteWorks
- CalculateLeaves, SelectSchedule
- Delete, Clear, Undo, Redo
2. /Logic/Parser
- Checked through all files, looks ok
3. /Model/Schedule
- Amended for all
Addtitional: 
- Added edit employee to menu bar
- Show ui on addSchedule, clearSchedule, calculateLeaves

V1.4.4 Java adoc comment in java

---

src/main/java/seedu/address/logic/parser/ModifyPayCommandParser.java
src/main/java/seedu/address/model/person/Salary.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/parser/ModifyPayCommandParserTest.java

ModifyPayCommandParserTest included

ModifyPay Parser test case

---

src/main/java/seedu/address/logic/parser/ModifyAllPayCommandParser.java
src/test/java/seedu/address/logic/parser/ModifyAllPayCommandParserTest.java

Include ModifyAllPayCommandParser Test

Updated test case for ModifyAllPayParser

---

src/main/java/seedu/address/model/VersionedModelList.java
src/test/java/seedu/address/commons/util/AppUtilTest.java
src/test/java/seedu/address/logic/commands/ClearCommandTest.java
src/test/java/seedu/address/logic/commands/DeleteScheduleCommandTest.java
src/test/java/seedu/address/ui/ResultDisplayTest.java
src/test/java/systemtests/AddCommandSystemTest.java

**Test files updated**
- VersionedModelList 100%
- AppUtil.java 100%
- Messages.java 100%

V1.4 Test files update

---

docs/UserGuide.adoc
docs/team/chuazhenwei.adoc

solving tag bug issue for portfolio and user guide

updated userguide and  personal portfolio

---

src/main/java/seedu/address/logic/commands/AddExpensesCommand.java
src/main/java/seedu/address/logic/parser/AddExpensesCommandParser.java
src/main/java/seedu/address/model/expenses/ExpensesAmount.java
src/test/data/XmlExpensesListStorageTest/invalidExpensesExpensesList.xml
src/test/data/XmlSerializableExpensesListTest/invalidExpensesExpensesList.xml
src/test/java/seedu/address/logic/commands/ClearExpensesCommandTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/RemoveExpensesCommandTest.java
src/test/java/seedu/address/logic/commands/SelectExpensesCommandTest.java
src/test/java/seedu/address/logic/parser/AddExpensesCommandParserTest.java
src/test/java/seedu/address/logic/parser/AddExpensesParserTest.java
src/test/java/seedu/address/logic/parser/RemoveExpensesCommandParserTest.java
src/test/java/seedu/address/logic/parser/SelectExpensesCommandParserTest.java
src/test/java/seedu/address/model/expenses/EmployeeIdExpensesContainsKeywordsPredicateTest.java
src/test/java/seedu/address/storage/XmlAdaptedExpensesTest.java
src/test/java/seedu/address/testutil/TypicalIndexes.java
src/test/java/seedu/address/testutil/expenses/TypicalExpenses.java

Update test files for all commands and parser under expenses except for add Expenses command and parser

V1.4.3 Update test files

---

docs/DeveloperGuide.adoc
docs/team/ryanchen2018.adoc
src/main/java/seedu/address/model/recruitment/JobDescription.java

- Add ’ into regex for job description. Notice that the right single quote in intelliJ is different from it shows in developer.

Recruitment v1.4.9
